import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "leaflet/dist/leaflet.css";
import GlobalErrorSuppressor from "@/components/GlobalErrorSuppressor";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: `
          window.onerror = function(msg, src, line, col, err) {
            if (typeof msg === 'string' && (msg.includes('conversation_id') || msg.includes('Cannot destructure property'))) return true;
            return false;
          };
          window.addEventListener('unhandledrejection', function(e) {
            var msg = e && e.reason && (e.reason.message || String(e.reason));
            if (msg && (msg.includes('conversation_id') || msg.includes('Cannot destructure property'))) e.preventDefault();
          });
        ` }} />
      </head>
      <body className="min-h-full flex flex-col">
        <GlobalErrorSuppressor />
        {children}
      </body>
    </html>
  );
}
